/******************************************************************************************************
* copyright © 2016
*
* File		: ps_GetMidLidTest.cls
*
* Purpose	: This is a batch class for other(any) Update. Thi class identified the records for other update 
*				and instanciates the service class to send the request to profitstars
*
*-----------------------------------------------------------------------------
*
*Release Date		Request 	Updated By			Description
*----------------------------------------------------------------------------------------------------------------------
*					Nill							Initial Creation
*
*09/13/2016			R163756		Rohit Kumar Malik	Create a batch to update MID and LIDs (GET Request) from ProfitStars
*09/13/2016			R164098
*
** Latest Changes 09/19/2016
*/
@isTest
public class ps_GetMidLidTest {
	static testmethod void batchGetMidLidTest(){
		//ps_GetMidLid fup = new ps_GetMidLid('', '');
	}
}